ugaty/priemnaya/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.main, name='main'),
    url(r'^get_message/$', views.get_message, name='get_message'),
]

ugaty/ugaty/urls.py
from __future__ import absolute_import, unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from wagtail.contrib.wagtailsitemaps.views import sitemap
from django.views.decorators.cache import cache_control


from wagtail.wagtailadmin import urls as wagtailadmin_urls
from wagtail.wagtailcore import urls as wagtail_urls
from wagtail.wagtaildocs import urls as wagtaildocs_urls

from search import views as search_views

urlpatterns = [
    url(r'^django-admin/', include(admin.site.urls)),

    url(r'^admin/', include(wagtailadmin_urls)),
    url(r'^documents/', include(wagtaildocs_urls)),

    url(r'^search/$', search_views.search, name='search'),
    url('^sitemap\.xml$', sitemap),
    # url('^robot\.txt$', sitemap),

    # For anything not caught by a more specific rule above, hand over to
    # Wagtail's page serving mechanism. This should be the last pattern in
    # the list:
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^vk_api/', include('vk.urls', namespace='vk')),
    url(r'^konference/', include('konference.urls', namespace='konference')),
    url(r'^annotate/', include('annotate.urls', namespace='annotate')),
    url(r'^priemnaya/', include('priemnaya.urls', namespace='priemnaya')),
    url(r'', include(wagtail_urls)),

    # Alternatively, if you want Wagtail pages to be served from a subpath
    # of your site, rather than the site root:
    #    url(r'^pages/', include(wagtail_urls)),
]


if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ugaty/vk/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^callback/$', views.callback, name='callback'),
]

ugaty/priemnaya/models.py
from django.db import models

class Message(models.Model):
    """ Список секций """

    name = models.CharField("От кого", max_length=300)
    email_tel = models.CharField("Способ связаться", max_length=300)
    message = models.TextField("Обращение")


    def __str__(self):
        return "{} {}".format(self.name, self.email_tel)

    class Meta():
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщения'
        ordering = ['name']

ugaty/priemnaya/views.py
from django.shortcuts import render

from .models import Message

# Create your views here.
def main(request):
    """ Приемная коммисия """

    return render(request, 'priemnaya/main.html')

def get_message(request):
    """ Получение обращения """

    print(request.POST)

    name = request.POST.get('name', False)
    email = request.POST.get('email', False)
    text = request.POST.get('text', False)

    if name and email and text:
        Message.objects.create(name=name, email_tel=email, message=text)
        return render(request, 'priemnaya/main.html',
                      {'status': 'Done'})
    else:
        return render(request, 'priemnaya/main.html',
                      {'status': 'Error'})

ugaty/priemnaya/templates/priemnaya/main.html
{% extends "base.html" %}

{% load wagtailcore_tags %}
{% load static wagtailuserbar %}
{% load wagtailcore_tags wagtailimages_tags %}
{% block body_class %}template-blogpage{% endblock %}
{% load blog_tags %}

{% block navs %}
  {% get_site_root as site_root %}
  {% top_menu parent=site_root calling_page=self %}
{% endblock %}

{% block content %}

  <div class="sending_message">
    
    <h1>Электронная приемная филиалла УГАТУ в городе Кумертау</h1>
    
    {% if status == "Done" %}
      <div class="jumbotron">
        <h1 class="display-4">Ваще обращение принято!</h1>
        <p class="lead">
          Теперь дождитесь обратной связи в близжайщее время. Мы с Вами обязательно свяжемся.
        </p>
      </div>
    {% elif status == 'Error' %}
      <div class="jumbotron">
        <h1 class="display-4">Ваще обращение не принято!</h1>
        <p class="lead">
          Увы и ах, что то произошло(или сломалось) в системе). Мы уже знаем о проблеме и скоро ее подправим. А пока можете обратиться по номеру <a href="tel:+73476141494">+7(34761)4–14–94</a> или <a href="tel:+73476142651"> +7(34761)4–26–51</a>
        </p>
      </div>
    {% endif %}

    <form action="{% url "priemnaya:get_message" %}" method="POST">
      {% csrf_token %}
      <div class="row">
        <div class="col-12 col-md-6 form-group">
          <label for="exampleFormControlInput1">Ваша электронная почта</label>
          <input type="email" class="form-control form-control-lg" id="exampleFormControlInput1" name="email" placeholder="Введите свой email, например: name@example.com" required>
        </div>

        <div class=" col-12 col-md-6 form-group">
          <label for="exampleFormControlInput1">Как к вам обращаться</label>
          <input type="text" class="form-control form-control-lg" id="exampleFormControlInput1" name="name" placeholder="Иванов Иван Иванович" required>
        </div>
      </div>

      <div class="form-group">
        <label for="exampleFormControlTextarea1">Ваще обращение</label>
        <textarea name="text" class="form-control" id="exampleFormControlTextarea1" rows="3" required></textarea>
      </div>

      <button type="submit" class="btn btn-primary btn-lg btn-block">Отправить</button>

    </form>

  </div>


{% endblock %}


{% block extra_js %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/info_page.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/priemnaya.css' %}">
{% endblock %}