ugaty/priemnaya/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.main, name='main'),
    url(r'^get_message/$', views.get_message, name='get_message'),
]

ugaty/ugaty/urls.py
from __future__ import absolute_import, unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from wagtail.contrib.wagtailsitemaps.views import sitemap
from django.views.decorators.cache import cache_control


from wagtail.wagtailadmin import urls as wagtailadmin_urls
from wagtail.wagtailcore import urls as wagtail_urls
from wagtail.wagtaildocs import urls as wagtaildocs_urls

from search import views as search_views

urlpatterns = [
    url(r'^django-admin/', include(admin.site.urls)),

    url(r'^admin/', include(wagtailadmin_urls)),
    url(r'^documents/', include(wagtaildocs_urls)),

    url(r'^search/$', search_views.search, name='search'),
    url('^sitemap\.xml$', sitemap),
    # url('^robot\.txt$', sitemap),

    # For anything not caught by a more specific rule above, hand over to
    # Wagtail's page serving mechanism. This should be the last pattern in
    # the list:
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^vk_api/', include('vk.urls', namespace='vk')),
    url(r'^konference/', include('konference.urls', namespace='konference')),
    url(r'^annotate/', include('annotate.urls', namespace='annotate')),
    url(r'^priemnaya/', include('priemnaya.urls', namespace='priemnaya')),
    url(r'', include(wagtail_urls)),

    # Alternatively, if you want Wagtail pages to be served from a subpath
    # of your site, rather than the site root:
    #    url(r'^pages/', include(wagtail_urls)),
]


if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ugaty/vk/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^callback/$', views.callback, name='callback'),
]

ugaty/ugaty/templates/base.html
{% load static wagtailuserbar %}
{% load render_top_menu %}

<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <title>
            {% block title %}
                {% if self.seo_title %}{{ self.seo_title }}{% else %}{{ self.title }}{% endif %}
            {% endblock %}
        </title>
        <meta name="description" content="{% block descr %} {% endblock %}" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="yandex-verification" content="e1053b9ad9537d4b" /> 
        <meta name="google-site-verification" content="oK0vqh_W22wiPjlBXg_3CBxlBEetU9uMMQNqU_FQpAM" /> 
      <!-- Chrome, Firefox OS and Opera -->
      <link rel="icon" type="image/png" href="{% static 'img/favicon.ico' %}" />
      <meta name="theme-color" content="#000">
      <!-- Windows Phone -->
      <meta name="msapplication-navbutton-color" content="#000">
      <!-- iOS Safari -->
      <meta name="apple-mobile-web-app-status-bar-style" content="#000">
        {# Global stylesheets #}
      <link rel="stylesheet" type="text/css" href="{% static 'css/preloader.css' %}">

        {% block extra_css %}
            {# Override this in templates to add extra stylesheets #}
        {% endblock %}
    </head>
    <body>
<div id="preloader">
  <div id="preloader_2" style="background-color: #1F3A93">
    <img src="{% static "img/puff.svg" %}" alt="">
  </div>
  <p>
  </p>
</div>      
    <nav class="navbar navbar-expand-lg navbar-dark nav-blue">
      <a class="navbar-brand" href="/">УГАТУ</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample08" aria-controls="navbarsExample08" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      
      <div class="collapse navbar-collapse justify-content-md-center" id="navbarsExample08">
        <ul class="navbar-nav nav_custom">
          {% get_site_root as site_root %}
          {% render_top_menu parent=site_root calling_page=self %}
        </ul>
      </div>

      <form action="{% url 'search' %}" method="get" class="search">
        <div class="input-group">
          <input class="form-control form-control-lg" size="8" type="text" placeholder="Поиск" name="query" >
          <div class="input-group-append">
            <button class="btn btn-outline-primary btn-lg" type="submit">
              <img src="{% static 'img/search.svg' %}" id="search" alt="">              
            </button>
          </div>                
        </div>
      </form>  
      <img src="{% static 'img/glaz.svg' %}" id="glaz" alt="">
    </nav>

  <div class="glaz_body">
    
  </div>

    {% block bottom %}
        
    {% endblock bottom %}

        {% wagtailuserbar %}

        {% block content %}{% endblock %}

<footer>
  <div class="container">
    <div class="row">
      <div class="col-lg-4">
        <p>ФГБОУ ВО  "Уфимский государственный авиационный технический университет" в г. Кумертау</p>
        <p>Мы так же есть в <a href="https://vk.com/ugatukf"><img src="{% static 'img/vk.svg' %}" alt="" class="icon_footer"></a></p>
      </div>
      <div class="col-lg-4">
        <p>
          453300, Республика Башкортостан, г. Кумертау, ул. М. Горького, 22А<br>
          <a href="tel:+73476142651"> (+734761)4–26–51</a><br>
          <a href="email:kumertau@ugatu.su">kumertau@ugatu.su</a>
        </p>
      </div>
      <div class="col-lg-4">
        <p>
          <a href="{% url 'priemnaya:main' %}">
          ЭЛЕКТРОННАЯ ПРИЕМНАЯ УГАТУ
Здесь Вы сможете задать вопрос администрации ВУЗа или оставить свое предложение
          </a>
        </p>
      </div>
    </div>
  </div>
</footer>
        {# Global javascript #}
        <script type="text/javascript" src="{% static 'js/preloader.js' %}"></script>
        <script
          src="https://code.jquery.com/jquery-3.3.1.min.js"
          integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
          crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
        <link rel="stylesheet" type="text/css" href="{% static 'css/main.min.css' %}">
        <script type="text/javascript" src="{% static 'js/glaz.js' %}"></script>
        {% block extra_js %}
            {# Override this in templates to add extra javascript #}
        {% endblock %}
    </body>
</html>